apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dailyevening
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dailyevening
            image: talele08/api-cronjob-image-4
            command: ["python3","cronJobAPIConfig.py"]
            args: ["dailyevening"]  
            env:
              - name: JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
          restartPolicy: OnFailure            
